product-name: VMware-NSX-T
product-properties:
  .properties.container_ip_blocks:
    value:
    - cidr: 192.168.208.0/20
      name: PAS-ORGS-IP-BLOCK
  .properties.enable_snat:
    value: true
  .properties.exit_on_disconnection:
    selected_option: enable
    value: enable
  .properties.external_ip_pools:
    value:
    - allocation_ranges: 192.168.33.11-192.168.33.253
      cidr: 192.168.33.0/24
      name: pas-floating-ip-pool
  .properties.foundation_name:
    value: kirklab-pas
  .properties.log_dropped_traffic:
    value: false
  .properties.ncp_debug_log:
    value: false
  .properties.nsx_api_ca_cert:
    value: |-
      -----BEGIN CERTIFICATE-----
      MIIDXjCCAkagAwIBAgIJALQ13ZkEuA3fMA0GCSqGSIb3DQEBCwUAMFoxCzAJBgNV
      BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMQswCQYDVQQHDAJDQTEMMAoGA1UE
      CgwDTlNYMRswGQYDVQQDDBJuc3gtbWdyLmtpcmtsYWIuaW8wHhcNMjAwMjAzMTU1
      MTE3WhcNMjUwMjAxMTU1MTE3WjBaMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2Fs
      aWZvcm5pYTELMAkGA1UEBwwCQ0ExDDAKBgNVBAoMA05TWDEbMBkGA1UEAwwSbnN4
      LW1nci5raXJrbGFiLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
      9JivvWrO5R8Rv1lQuF1GTp2bFbMThjVEd44az9RH1TueQ1w6HEPd7drt+omztIpr
      13Jmcvq+uniADqpEgGUxm9ud6QEiUTk1n3Ngs8HCwAUPnTwcHmZ9PWi4qwQT3NP9
      GEiLZjZ4BPict2h5fGxqEpJl5ATR4Ghzqxju5rXUC6OcTcVhf+dZolHpWn2jHvdW
      QdpU777H6jPsFbDUOYd4vL/iu4zLPqjwjAWxs+hl85OOEOOmMBLqwjukFz3eUITE
      359ZjLkIUNvjQq5N/iG2q4xGfrjidrsV639mCkcbrT4ZrhCYr5d71KgYTp7F9ALs
      4DnLUtLvK82B15hHFn0lRQIDAQABoycwJTAjBgNVHREEHDAaghJuc3gtbWdyLmtp
      cmtsYWIuaW+HBMCoDAcwDQYJKoZIhvcNAQELBQADggEBAAGYIWqjTpZRY2QzFrFn
      GmfUjl1GHzMSqFGndrHUBNbT48t9nnDqXEijHUlMjmgKiQPsjff4Gy7S1X/1YZ1N
      Ll3y1zJg/upOGN5invTzAT29jjZsMIEKhfz2amLD0FCPIePZv/thkQKyL6t98+N9
      EUYDpsTxT0lfa8j4bBLpz/CS+rqlo1ODI/AGsvOFcf4Ottq0clBbmW2EWngEfqMr
      mvWviMxgTE7nYyGrT62sxnq9DUuQ7wjDVVvza8b0HVWXzDufPGNZzMaoh6AOdJzK
      4N9nlFJXtZjaWIkM77PGvyE/OZyz0GSZ6IQ7IcXHSGLuWGXT8N3pYxrHBau3dw2I
      bbU=
      -----END CERTIFICATE-----
  .properties.nsx_api_managers:
    value: nsx-mgr.kirklab.io
  .properties.nsx_auth:
    selected_option: simple
    value: simple
  .properties.nsx_auth.simple.nsx_api_password:
    value:
      secret: ((properties_nsx_auth_simple_nsx_api_password.secret))
  .properties.nsx_auth.simple.nsx_api_user:
    value: admin
  .properties.nsx_node_agent_debug_log:
    value: false
  .properties.overlay_tz:
    value: TZ-Overlay
  .properties.subnet_prefix:
    value: 24
  .properties.tier0_router:
    value: t0-pks

