---
opsman-configuration:
  vsphere:
    vcenter:
      url: vcenter.kirklab.io
      username: administrator@vsphere.local
      password: ((vcenter-password))
      datastore: carbonite
      #ca_cert: certificate
      #host: 192.168.10.8                     # vCenter host to deploy Ops Manager in
      datacenter: kirklab
      resource_pool: /kirklab/host/kirklab-cluster/Resources/RP-CONTROL # or /<Data Center Name>/host/<Cluster Name>
      folder: /kirklab/vm/control_vms
      insecure: 1                            # default: 0 (secure); 1 (insecure)
    disk_type: thin                          # example: thin|thick
    private_ip: 192.168.40.2
    dns: 192.168.1.1
    ntp: time1.google.com                    # example: ntp.ubuntu.com
    #ssh_password: ((opsman-password))
    ssh_public_key: ((opsman-public-ssh-key))           # for OpsManager >= 2.3
    hostname: opsman.control.kirklab.io
    network: Control-VLAN40-PG                 # vcenter network to deploy to
    netmask: 255.255.255.0
    gateway: 192.168.40.1
    vm_name: Control_Ops_Manager                     # default: Ops_Manager
    memory: 8                                # default: 8 GB
    cpu: 1                                   # default: 1